# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - master
      - test

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.21.5'

    - name: Build
      run: |
        cd server
        go build -v ./cmd/main.go

    - name: Test
      run: |
        cd server
        go test -timeout 30s -run ^TestGenerateChecksum$ rpc_demo_server/pkg/protocol
        go test -timeout 30s -run ^TestParsePayloadToFloat64s_normal$ rpc_demo_server/pkg/protocol
