name: Rust

on:
  push:
    branches: 
      - master
      - test/*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd client
        cargo build --verbose

    - name: Run tests
      run: |
        cd client
        cargo test --verbose
